
# -*- coding: utf-8 -*-
"""Sabia8B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9ChP_9ZTODvEbfZ9WgZZ3FxX7whgOz4
"""


# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
# kagglehub.login()

rfdornelles_lacerda_path = "../data/" #kagglehub.dataset_download('rfdornelles/lacerda')
rfdornelles_prompt_path = "../prompt/" # kagglehub.dataset_download('rfdornelles/prompt')
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import os
# if "COLAB_" not in "".join(os.environ.keys()):
#     !pip install unsloth
# else:
#     # Do this only in Colab notebooks! Otherwise use pip install unsloth
#     !pip install --no-deps bitsandbytes accelerate xformers==0.0.29.post3 peft trl==0.15.2 triton cut_cross_entropy unsloth_zoo
#     !pip install sentencepiece protobuf datasets huggingface_hub hf_transfer
#     !pip install --no-deps unsloth
#

import os
CUDA_VISIBLE_DEVICES = "3" # Set this to the GPUs you want to use
os.environ["CUDA_VISIBLE_DEVICES"] = CUDA_VISIBLE_DEVICES

from unsloth import FastLanguageModel
import torch
from unsloth.chat_templates import get_chat_template
from unsloth.chat_templates import standardize_data_formats
from unsloth.chat_templates import train_on_responses_only
from unsloth import unsloth_train

from trl import SFTTrainer, SFTConfig
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from unsloth import is_bfloat16_supported

from transformers import EarlyStoppingCallback
from datasets import load_from_disk
import torch
import wandb
import datetime
import os
# os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "garbage_collection_threshold:0.6,max_split_size_mb:128"
print("Packages loaded!")

## Configuration
ckpt = "maritaca-ai/sabia-7b"
max_seq_length = 2048 * 9
num_train_epochs = 10
full_finetuning = False
now = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
experiment_name = f"ft_{'full' if full_finetuning else 'lora'}_{ckpt.split('/')[1]}_v1_{now}"

folder = f"ft_sabia-7b_unsloth"
os.makedirs(folder, exist_ok=True)

print("Config done!")

model, tokenizer = FastLanguageModel.from_pretrained(
  model_name = ckpt,
  attn_implementation='eager',
  dtype=None,
  max_seq_length = max_seq_length, # Choose any for long context!
  load_in_4bit = False,  # 4 bit quantization to reduce memory
  load_in_8bit= True,
  full_finetuning = full_finetuning, # [NEW!] We have full finetuning now!
  # token = "hf_...", # use one if using gated models
  device_map = "auto",  # Map model layers to CUDA devices 1, 2, and 3 (via CUDA_VISIBLE_DEVICES)
  # use_gradient_checkpointing=True
)

## peft
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
    # finetune_vision_layers     = False, # Turn off for just text!
    # finetune_language_layers   = True,  # Should leave on!
    # finetune_attention_modules = True,  # Attention good for GRPO
    # finetune_mlp_modules       = True,  # SHould leave on always!

)



print("Model and tokenizer loaded!!")

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama",
)

train = load_from_disk(f"{rfdornelles_lacerda_path}/train")
train = standardize_data_formats(train)

test = load_from_disk(f"{rfdornelles_lacerda_path}/validation")
test = standardize_data_formats(test)

with open(f"{rfdornelles_prompt_path}/prompt_v4.md", "r") as f:
    prompt = f.read()

def build_template(batch):
    outputs = []
    # Itera sobre cada par input/output do batch
    for inp, out in zip(batch["input"], batch["output"]):
        messages = [
            {'role': 'user', 'content': prompt + f"----- Sentença judicial:     {inp}"},
            {'role': 'assistant', 'content': out}
        ]
        # Aplica o template para cada exemplo e adiciona o resultado na lista
        outputs.append(tokenizer.apply_chat_template(messages, tokenize = False, add_generation_prompt = False,
                                                     max_length=max_seq_length))
    return {"text": outputs}

train = train.map(build_template, batched=True)
test = test.map(build_template, batched=True)
print("Train and test datasets loaded!!")









# model.push_to_hub(f"{experiment_name}_model", private=True)
# tokenizer.push_to_hub(f"{experiment_name}_tokenizer", private=True)
#model.save_pretrained_merged(experiment_name, tokenizer)

trainer = SFTTrainer(
    output_dir = folder,
    model = model,
    tokenizer = tokenizer,
    train_dataset = train,
    eval_dataset = test,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer),
    dataset_num_proc = 1,
    # packing = False, # Can make training 5x faster for short sequences.
    args = SFTConfig( #TrainingArguments(
        per_device_train_batch_size = 1,
        per_device_eval_batch_size= 1,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        num_train_epochs = num_train_epochs, # Set this for 1 full training run.
        # max_steps = 60,
        learning_rate = 2e-5,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = f"outputs_{experiment_name}",
        run_name=f"{experiment_name}",
        report_to = "wandb", # Use this for WandB etc
        load_best_model_at_end=True,
        save_strategy = "steps",
        save_steps = 10,  # [NEW!] Save model every 10,000 steps
        save_total_limit=3,
        metric_for_best_model= "eval_loss",
        eval_strategy = "steps",
        eval_steps=10,
        # greater_is_better=False,
    ),
    callbacks=[
      EarlyStoppingCallback(early_stopping_patience=5),
    ],
)

# trainer = train_on_responses_only(
#     trainer,
#     instruction_part="<|im_start|>user<|im_sep|>",
#     response_part="<|im_start|>assistant<|im_sep|>",
# )

print("Trainer loaded!!")

# Initialize wandb
# wandb.login()
# Set the wandb project name

wandb.init(name=f"{experiment_name}")

print("Starting fine-tuning....")
trainer_stats = unsloth_train(trainer,resume_from_checkpoint = True ) # trainer.train() #
print(trainer_stats)
wandb.finish()


print("Training finished!!")
print("Saving model and tokenizer....")


try:
  model.save_pretrained(f"{experiment_name}_model")  # Local saving
  print(" Model saved!!")
except Exception as e:
  print(f"Error saving model: {e}")

try:
  tokenizer.save_pretrained(f"{experiment_name}_tokenizer")  # Local saving
  print("Tokenizer saved!!")
except Exception as e:
  print(f"Error saving tokenizer: {e}")

try:
  model.save_pretrained_merged(experiment_name, tokenizer)
  print("Model and tokenizer saved!!")
except Exception as e:
  print(f"Error saving model and tokenizer: {e}")

torch.cuda.empty_cache()
print("Finishing!")