# -*- coding: utf-8 -*-
"""Tucano-Inference_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExQzOO6a-PMX3agQtfKyEp1SAU3PTYzR

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://docs.unsloth.ai/get-started/installing-+-updating).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save)

### News

**Read our [Gemma 3 blog](https://unsloth.ai/blog/gemma3) for what's new in Unsloth and our [Reasoning blog](https://unsloth.ai/blog/r1-reasoning) on how to train reasoning models.**

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation
"""

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3" # Change this to your GPU ID


from unsloth import FastLanguageModel
import torch
from unsloth.chat_templates import get_chat_template
from unsloth.chat_templates import standardize_data_formats

from datasets import load_from_disk
import torch
import datetime


# clean cuda just in case
torch.cuda.empty_cache()

# definitions
experiment = 'experiment_tucanobr_ft_v2_unsloth_inference'
folder = f'../experiments/{experiment}'

os.makedirs(folder, exist_ok=True)

## Configuration
ckpt = "rfdornelles/master_thesis_tucanobr_2b4_ft" #"unsloth/Phi-4"
max_seq_length = 2048 * 9
num_train_epochs = 10
full_finetuning = False
now = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
experiment_name = f"run_unsloth_{'full' if full_finetuning else 'lora'}_{ckpt.split('/')[1]}_v1_{now}"
folder = f"{experiment_name}"
print("Config done!")

model, tokenizer = FastLanguageModel.from_pretrained(
  model_name = ckpt,
  attn_implementation='eager',
  dtype=None,
  max_seq_length = max_seq_length, # Choose any for long context!
  load_in_4bit = False,  # 4 bit quantization to reduce memory
  load_in_8bit= True,
  full_finetuning = full_finetuning, # [NEW!] We have full finetuning now!
  # token = "hf_...", # use one if using gated models
  # device_map = "auto",  # Map model layers to CUDA devices 1, 2, and 3 (via CUDA_VISIBLE_DEVICES)
  # use_gradient_checkpointing=True
)

## peft
model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    # use_rslora = False,  # We support rank stabilized LoRA
    # loftq_config = None, # And LoftQ
    # finetune_vision_layers     = False, # Turn off for just text!
    # finetune_language_layers   = True,  # Should leave on!
    # finetune_attention_modules = True,  # Attention good for GRPO
    # finetune_mlp_modules       = True,  # SHould leave on always!

)

# tokenizer = get_chat_template(
#     tokenizer,
#     chat_template = "gpt2"#"phi-4",
# )
model = model.to("cuda")

print("Model and tokenizer loaded!!")


# tokenizer = get_chat_template(
#     tokenizer,
#     chat_template = "llama3",
#     mapping = {"role" : "from", "content" : "value", "user" : "human", "assistant" : "gpt"}, # ShareGPT style
# )
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

"""Change the "value" part to call the model!

Unsloth makes inference natively 2x faster!! No need to change or do anything!
"""


test = load_from_disk(".../data/test")
test = standardize_data_formats(test)

with open(f"../prompt/prompt_v4.md", "r") as f:
    prompt = f.read()

def build_template(batch):
    outputs = []
    # Itera sobre cada par input/output do batch
    for inp, out in zip(batch["input"], batch["output"]):
        messages = [
            {'role': 'user', 'content': prompt + f"----- Sentença judicial:     {inp}"},
            {'role': 'assistant', 'content': out}
        ]
        # Aplica o template para cada exemplo e adiciona o resultado na lista
        outputs.append(tokenizer.apply_chat_template(messages, tokenize = False, add_generation_prompt = False, max_length=max_seq_length))
    return {"text": outputs}

test = test.map(build_template, batched=True)
print("Train and test datasets loaded!!")

alpaca_prompt = """
### Instruction:
{}

### Input:
{}

### Response:
{}"""

EOS_TOKEN = tokenizer.eos_token # Must add EOS_TOKEN

def formatting_prompts_func(sentenca):
    instructions = prompt
    inputs       = sentenca
    outputs      = ""
    texts = []

    for instruction, input, output in zip(instructions, inputs, outputs):
        # Must add EOS_TOKEN, otherwise your generation will go on forever!
        text = alpaca_prompt.format(instruction, input, output) + EOS_TOKEN
        texts.append(text)
    return { "text" : texts, }
pass

def run_model(processo, new_tokens=1000, overwrite = False):

  # clean: remove everything that's not numbers
  processo = str(processo).replace(r'[^0-9]', '')

  # check if the file already exists
  file = f'{folder}/{processo}.json'

  if os.path.exists(file) and not overwrite:
    print(f"File {file} already exists. Skipping...")
    return

  print(f"  Processing {processo}...")
  # retrieve the content of the sentença
  sentenca = test.filter(lambda x: x['processo'] == processo)['input'][0]

  # build the prompt
  message = [
            {"role": "user", "content": prompt + sentenca},
            {"role": "assistant", "content": ""}
    ]

  # run the model
  try:
    print(f"  Applying chat template for {processo}")
    inputs = tokenizer.apply_chat_template(
        message,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt"
    ).to(model.device)

    input_len = inputs["input_ids"].shape[-1]

    print(f"  Generating for {processo}")
    generation = model.generate(**inputs,
                                max_new_tokens=new_tokens, do_sample=False,
                                temperature=None,
                                top_p=None,
                                top_k=None)

    print(f"  Decoding for {processo}")
    # only keep the new tokens
    generation = generation[0][input_len:]

    print("  Decoding the generation...")
    decoded = tokenizer.decode(generation, skip_special_tokens=True)

  except Exception as e:
    print(f"Error processing {processo}: {e}")
    return


  # save the output as json
  print(f"  Saving the output for {processo}...")
  try:
    with open(file, 'w') as f:
      f.write(decoded)
      return True

  except Exception as e:
    print(f"Error writing file {file}: {e}")
    return

os.makedirs(folder, exist_ok=True)
for processo in test['processo']:
  run_model(processo)

print("End")